// Generated by build/write_buildflag_header.py
// From "//mojo/public/cpp/bindings:mojo_buildflags"

#ifndef MOJO_PUBLIC_CPP_BINDINGS_MOJO_BUILDFLAGS_H_
#define MOJO_PUBLIC_CPP_BINDINGS_MOJO_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_MOJO_TRACE_ENABLED() (0)
#define BUILDFLAG_INTERNAL_MOJO_RANDOM_DELAYS_ENABLED() (0)

#endif  // MOJO_PUBLIC_CPP_BINDINGS_MOJO_BUILDFLAGS_H_
