// Generated by build/write_buildflag_header.py
// From "//ipc:ipc_buildflags"

#ifndef IPC_IPC_BUILDFLAGS_H_
#define IPC_IPC_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_IPC_MESSAGE_LOG_ENABLED() (0)

#endif  // IPC_IPC_BUILDFLAGS_H_
