// vendor/chromium/mojo/public/mojom/base/big_buffer.mojom-params-data.h is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef VENDOR_CHROMIUM_MOJO_PUBLIC_MOJOM_BASE_BIG_BUFFER_MOJOM_PARAMS_DATA_H_
#define VENDOR_CHROMIUM_MOJO_PUBLIC_MOJOM_BASE_BIG_BUFFER_MOJOM_PARAMS_DATA_H_

#include "base/logging.h"
#include "base/macros.h"
#include "mojo/public/cpp/bindings/lib/bindings_internal.h"
#include "mojo/public/cpp/bindings/lib/buffer.h"
#include "mojo/public/cpp/bindings/lib/validation_context.h"

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-private-field"
#elif defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable:4056)
#pragma warning(disable:4065)
#pragma warning(disable:4756)
#endif
namespace mojo_base {
namespace mojom {
namespace internal {

}  // namespace internal
}  // namespace mojom
}  // namespace mojo_base

#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif

#endif  // VENDOR_CHROMIUM_MOJO_PUBLIC_MOJOM_BASE_BIG_BUFFER_MOJOM_PARAMS_DATA_H_