// vendor/chromium/mojo/public/mojom/base/text_direction.mojom-import-headers.h is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef VENDOR_CHROMIUM_MOJO_PUBLIC_MOJOM_BASE_TEXT_DIRECTION_MOJOM_IMPORT_HEADERS_H_
#define VENDOR_CHROMIUM_MOJO_PUBLIC_MOJOM_BASE_TEXT_DIRECTION_MOJOM_IMPORT_HEADERS_H_

#endif  // VENDOR_CHROMIUM_MOJO_PUBLIC_MOJOM_BASE_TEXT_DIRECTION_MOJOM_IMPORT_HEADERS_H_