export default {
  "fxdk-theme": "https://static.cfx-services.net/fxdk-theia-plugins/fxdk-theme.1.51.1.vsix",
  "fxdk-ts-plugin": "https://static.cfx-services.net/fxdk-theia-plugins/fxdk-ts-plugin.1.51.1.vsix",
  "vscode-builtin-xml": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.xml-1.51.1.vsix",
  "vscode-builtin-css": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.css-1.51.1.vsix",
  "vscode-builtin-css-language-features": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.css-language-features-1.51.1.vsix",
  "vscode-builtin-html": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.html-1.51.1.vsix",
  "vscode-builtin-html-language-features": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.html-language-features-1.51.1.vsix",
  "vscode-builtin-javascript": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.javascript-1.51.1.vsix",
  "vscode-builtin-json": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.json-1.51.1.vsix",
  "vscode-builtin-markdown": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.markdown-1.51.1.vsix",
  "vscode-builtin-markdown-language-features": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.markdown-language-features-1.51.1.vsix",
  "vscode-builtin-npm": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.npm-1.51.1.vsix",
  "vscode-builtin-log": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.log-1.51.1.vsix",
  "vscode-builtin-lua": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.lua-1.51.1.vsix",
  "vscode-builtin-csharp": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.csharp-1.51.1.vsix",
  "vscode-builtin-csharp-language-features": "https://static.cfx-services.net/fxdk-theia-plugins/ms-dotnettools.csharp-1.23.8.vsix",
  "vscode-builtin-scss": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.scss-1.51.1.vsix",
  "vscode-builtin-typescript": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.typescript-1.51.1.vsix",
  "vscode-builtin-typescript-language-features": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.typescript-language-features-1.51.1.vsix",
  "vscode-builtin-theme-monokai": "https://static.cfx-services.net/fxdk-theia-plugins/vscode.theme-monokai-1.51.1.vsix"
}
