// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220110.5

#pragma once
#include "winrt/CitiLaunch.h"
#include "winrt/Windows.UI.Composition.h"
#include "winrt/Windows.UI.Xaml.h"
#include "winrt/Windows.UI.Xaml.Media.h"
namespace winrt::CitiLaunch::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) BackdropBrush_base : implements<D, CitiLaunch::BackdropBrush, composing, winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverrides, winrt::Windows::UI::Xaml::Media::IBrushOverrides2, I...>,
        impl::require<D, winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBase, winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBaseProtected, winrt::Windows::UI::Xaml::Media::IBrush, winrt::Windows::UI::Composition::IAnimationObject, winrt::Windows::UI::Xaml::IDependencyObject, winrt::Windows::UI::Xaml::IDependencyObject2>,
        impl::base<D, winrt::Windows::UI::Xaml::Media::XamlCompositionBrushBase, winrt::Windows::UI::Xaml::Media::Brush, winrt::Windows::UI::Xaml::DependencyObject>,
        winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBaseOverridesT<D>, winrt::Windows::UI::Xaml::Media::IBrushOverrides2T<D>
    {
        using base_type = BackdropBrush_base;
        using class_type = CitiLaunch::BackdropBrush;
        using implements_type = typename BackdropBrush_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Windows::UI::Xaml::Media::XamlCompositionBrushBase;
        hstring GetRuntimeClassName() const
        {
            return L"CitiLaunch.BackdropBrush";
        }
        BackdropBrush_base()
        {
            impl::call_factory<winrt::Windows::UI::Xaml::Media::XamlCompositionBrushBase, winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBaseFactory>([&](winrt::Windows::UI::Xaml::Media::IXamlCompositionBrushBaseFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::CitiLaunch::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) BackdropBrushT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = CitiLaunch::BackdropBrush;

        hstring GetRuntimeClassName() const
        {
            return L"CitiLaunch.BackdropBrush";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_BACKDROPBRUSH_XAML_G_H) || __has_include("CitiLaunch/BackdropBrush.xaml.g.h")
#include "CitiLaunch/BackdropBrush.xaml.g.h"
#else

namespace winrt::CitiLaunch::implementation
{
    template <typename D, typename... I>
    using BackdropBrushT = BackdropBrush_base<D, I...>;
}

#endif
