// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once

WINRT_EXPORT namespace winrt::CitiLaunch {

struct IBackdropBrush;
struct BackdropBrush;

}

namespace winrt::impl {

template <> struct category<CitiLaunch::IBackdropBrush>{ using type = interface_category; };
template <> struct category<CitiLaunch::BackdropBrush>{ using type = class_category; };
template <> struct name<CitiLaunch::IBackdropBrush>{ static constexpr auto & value{ L"CitiLaunch.IBackdropBrush" }; };
template <> struct name<CitiLaunch::BackdropBrush>{ static constexpr auto & value{ L"CitiLaunch.BackdropBrush" }; };
template <> struct guid_storage<CitiLaunch::IBackdropBrush>{ static constexpr guid value{ 0xB3CC91C9,0xD1CB,0x5350,{ 0xBC,0x5C,0xA0,0x76,0xF5,0xC5,0x0B,0xF7 } }; };
template <> struct default_interface<CitiLaunch::BackdropBrush>{ using type = CitiLaunch::IBackdropBrush; };

template <> struct abi<CitiLaunch::IBackdropBrush>{ struct type : IInspectable
{
};};

template <typename D>
struct consume_CitiLaunch_IBackdropBrush
{
};
template <> struct consume<CitiLaunch::IBackdropBrush> { template <typename D> using type = consume_CitiLaunch_IBackdropBrush<D>; };

}
