// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Windows.UI.Composition.0.h"
#include "winrt/impl/Windows.UI.Xaml.0.h"
#include "winrt/impl/Windows.UI.Xaml.Media.0.h"
#include "winrt/impl/CitiLaunch.0.h"

WINRT_EXPORT namespace winrt::CitiLaunch {

struct WINRT_EBO IBackdropBrush :
    Windows::Foundation::IInspectable,
    impl::consume_t<IBackdropBrush>
{
    IBackdropBrush(std::nullptr_t = nullptr) noexcept {}
};

}
