// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.190111.3

#pragma once
#include "winrt/impl/Microsoft.Graphics.Canvas.Effects.0.h"

WINRT_EXPORT namespace winrt::Microsoft::Graphics::Canvas::Effects {

}
