// Copyright (c) 2015 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/cpptoc/set_cookie_callback_cpptoc.h"


// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK set_cookie_callback_on_complete(
    struct _cef_set_cookie_callback_t* self, int success) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;

  // Execute
  CefSetCookieCallbackCppToC::Get(self)->OnComplete(
      success?true:false);
}


// CONSTRUCTOR - Do not edit by hand.

CefSetCookieCallbackCppToC::CefSetCookieCallbackCppToC(
    CefSetCookieCallback* cls)
    : CefCppToC<CefSetCookieCallbackCppToC, CefSetCookieCallback,
        cef_set_cookie_callback_t>(cls) {
  struct_.struct_.on_complete = set_cookie_callback_on_complete;
}

#ifndef NDEBUG
template<> base::AtomicRefCount CefCppToC<CefSetCookieCallbackCppToC,
    CefSetCookieCallback, cef_set_cookie_callback_t>::DebugObjCt = 0;
#endif

