#pragma once

static const std::map<std::string, std::string, std::less<>> g_rosErrors{
	{ "Errors_1000", "An unknown error occurred. Please try again later. If the error persists, please visit the <a>Rockstar Support</a> website and stay tuned to Service Status Updates." },
	{ "Errors_1000.186", "Error response received from Epic. Please try again later. If the issue continues, please contact <a>Epic Support</a>." },
	{ "Errors_1000.50", "Error response received from Steam. Please try again later. If the issue continues, please contact <a>Steam Support</a>." },
	{ "Errors_1001", "The Rockstar Game Services timed out. Please try again later." },
	{ "Errors_1002", "This feature requires a service that is currently disabled. Please try again later. If the error persists, please visit the <a>Rockstar Support</a> website and stay tuned to Service Status Updates." },
	{ "Errors_1002.24", "This feature requires a service that is currently disabled for maintenance. Please try again later." },
	{ "Errors_1003.50", "We are currently experiencing communication problems with Steam. Please try again later. If the issue persists, please check our <a>Service Status page</a>." },
	{ "Errors_1004", "Data is not accessible. There may be a connection problem with your network. Please ensure you have internet access and try again." },
	{ "Errors_1004.208", "There may be a connection problem with your network. Please ensure you have internet access and try again." },
	{ "Errors_1004.50", "An authentication error occurred, this may be because the Steam client is offline. Please check Steam connectivity and try again." },
	{ "Errors_2002.50", "Error response received from Steam. Please try again later. If the issue continues, please contact <a>Steam Support</a>." },
	{ "Errors_3000", "Unfortunately we failed to fetch an essential asset. Please try again later." },
	{ "Errors_3000.18", "Failed to fetch countries due to a problem with Rockstar Game Services. Please try again later." },
	{ "Errors_3000.19", "Unfortunately we failed to fetch policy documents. Please try again later." },
	{ "Errors_3001", "Failed to retrieve Social Club data due to a problem with Rockstar Game Services. Please try again later." },
	{ "Errors_3002", "Failed to retrieve Social Club data due to a problem with Rockstar Game Services. Please try again later." },
	{ "Errors_4000", "Authentication failed. Please try again later." },
	{ "Errors_4000.101", "Authentication failed. Please check your Verification Code and try again." },
	{ "Errors_4000.102", "Authentication failed. Please check your Verification Code and try again." },
	{ "Errors_4000.103", "Authentication failed. Please check your Verification Code and try again." },
	{ "Errors_4000.105", "Authentication failed. Please check your Verification Code and try again." },
	{ "Errors_4000.11", "You have been logged out because your Email is no longer valid. Please login again to continue using the Rockstar Games Launcher" },
	{ "Errors_4000.115", "Authentication failed. Please check your Verification Code and try again." },
	{ "Errors_4000.119", "2-Step Authentication failed, too many attempts." },
	{ "Errors_4000.183", "Sorry, we are unable to handle your request at this time. Please try again later." },
	{ "Errors_4000.205", "We were unable to verify your account details at this time. Please try again later. If the problem persists, please visit the <a>Rockstar Games Support</a> site." },
	{ "Errors_4000.23", "Too many failed login attempts. Please try again later." },
	{ "Errors_4000.50", "Steam authentication failed. Please try again later." },
	{ "Errors_4000.51", "You have been logged out because your authentication ticket is no longer valid. Please login again to continue using the Rockstar Games Launcher" },
	{ "Errors_4000.89", "You have been logged out because your account has logged in elsewhere. Please login again to continue using the Rockstar Games Launcher" },
	{ "Errors_4000.95", "Your saved sign in token has expired, please sign in again." },
	{ "Errors_4000.96", "Authentication failed. Please check your password and try again." },
	{ "Errors_4001", "Not allowed. Please contact <a>Technical Support</a> for assistance." },
	{ "Errors_4001.100", "This account is not allowed to use the Custom Avatar feature due to past violations of our <a>Code of Conduct</a>." },
	{ "Errors_4001.11", "This feature is not currently available.  Please contact <a>Technical Support</a> for assistance." },
	{ "Errors_4001.113", "Rockstar Games Launcher does not currently support being run directly.  Please launch your game instead." },
	{ "Errors_4001.209", "We could not send you an email at this time because you have already reached the daily limit for account verification requests. Please check your junk mail folder if you previously requested an email, or try again in 24 hours." },
	{ "Errors_4001.25", "We could not send you a password reset confirmation email at this time because you have already reached the daily limit for password reset requests. Please check your junk mail folder if you previously requested a password reset, or try again in 24 hours." },
	{ "Errors_4001.34", "Only Social Club accounts can link to Steam." },
	{ "Errors_4001.38", "You are not allowed to use this feature of Social Club. For more information, please refer to our <a>Code of Conduct</a>." },
	{ "Errors_4001.46", "You cannot message yourself." },
	{ "Errors_4001.49", "Account linking failed. This Steam account is already linked to a different Social Club account.  Please log in with that Social Club account instead." },
	{ "Errors_4001.72", "Unable to update nickname because it has already been changed in the last 365 days." },
	{ "Errors_4001.79", "Unable to perform this action because the requested player account could not be found." },
	{ "Errors_4001.81", "This Social Club account is already linked to a different Steam account. Please log out of Steam and log in on the Steam account linked to this Social Club account." },
	{ "Errors_5000", "There is a missing value, please check any input you've provided and try again.  If the issue persists, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5000.185", "Unable to locate Epic Access Token, please try again.  If the issue persists, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5000.46", "The message does not contain any text. Please enter a message and try again." },
	{ "Errors_5000.51", "There is a missing authentication value, please try again.  If the issue persists, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5000.66", "The Store is currently unable to complete your order.  Please try again later." },
	{ "Errors_5000.76", "Unable to locate Steam App Id, please try again.  If the issue persists, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5000.77", "Unable to locate Steam Auth Ticket, please try again.  If the issue persists, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5001", "Unable to process request due to a problem with Rockstar Game Services reporting this input as invalid. Please try again later." },
	{ "Errors_5001.11", "Unable to update account due to an invalid email address. Please try again with a valid email address. Only alphanumeric characters, numbers, underscores, periods, and \"@\" symbols are currently allowed." },
	{ "Errors_5001.27", "Invalid characters in Nickname." },
	{ "Errors_5001.31", "Password must contain {min}-{max} characters with at least one number, one uppercase character and one lowercase character. Please amend your password and try again." },
	{ "Errors_5001.5", "Unable to process request due to a missing or invalid avatar url. This most commonly occurs due an issue with the Social Club. Please try again. If the issue persists, make sure you are using the latest version of the Social Club application, found here: <a>https://support.rockstargames.com/hc/articles/200146066</a>." },
	{ "Errors_5001.50", "Rockstar Services are experiencing problems communicating with Steam. Please try again later. If the issue continues, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5001.8", "Unable to process request because the Social Club detected a missing or invalid country code. Please try again. If the issue persists, make sure you are using the latest version of the Social Club application, found here:  <a>https://support.rockstargames.com/hc/articles/200146066</a>." },
	{ "Errors_5002", "Invalid data. Please try again later. If the issue continues, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5002.10", "Unable to retrieve account because it contains an invalid DOB. Please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5002.11", "Unable to retrieve account because it contains an invalid email address.  Please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5002.33", "Unable to retrieve account because it contains an invalid phone number.  Please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5002.50", "Unable to read response from Steam. Please try again later. If the issue continues, please contact <a>Steam Support</a>." },
	{ "Errors_5002.62", "Unable to retrieve account because it contains an invalid zip code.  Please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5002.77", "Attempting to set Steam auth ticket to empty value. Please try again later. If the issue continues, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5002.93", "Only alphanumeric characters supported for this input. Please switch IME modes." },
	{ "Errors_5003", "Unable to process invalid account data from the server. If the issue persists, please contact <a>Technical Support</a> for assistance." },
	{ "Errors_5003.27", "Nickname must contain between 6 and 16 characters. Please amend your nickname and try again." },
	{ "Errors_5003.28", "Nickname must contain between 6 and 16 characters. Please amend your nickname and try again." },
	{ "Errors_5003.32", "Password must contain {min}-{max} characters. Please amend your password and try again." },
	{ "Errors_5003.66", "The Store is currently unable to complete your order.  Please try again later." },
	{ "Errors_5003.78", "You have exceeded the maximum number of Crews." },
	{ "Errors_5004", "The request contains profanity, reserved words, or other disallowed terms. Please remove this text and try again." },
	{ "Errors_5004.27", "The nickname contains profanity, reserved words, or other disallowed terms." },
	{ "Errors_5005", "Data validation failed." },
	{ "Errors_5005.74", "Unsafe input detected. Please remove this text and try again." },
	{ "Errors_6000", "The requested data does not exist." },
	{ "Errors_6000.35", "The requested Player Account does not exist." },
	{ "Errors_6000.41", "The requested Rockstar Account does not exist." },
	{ "Errors_6000.51", "You have been logged out because your authentication ticket is no longer valid. Please login again to continue using the Rockstar Games Launcher" },
		{ "Errors_6000.80", "Online sign in failed. We attempted to fallback to offline sign in but that also failed. The username or password may be wrong or the account may not exist on this machine. Offline play is only available for accounts that have previously signed in on this machine (with \"Remember me\" ticked) while connected to the Internet and while Social Club Services are available.\r\n" },
	{ "Errors_6000.85", "You do not have an invitation to join this crew." },
		{ "Errors_6000.87", "Online sign in failed. We were unable to fallback to offline sign in because you have not previously signed in on this machine. Offline play is only available for accounts that have previously signed in on this machine (with \"Remember me\" ticked) while connected to the Internet and while Social Club Services are available." },
	{ "Errors_6000.88", "The product you attempted to purchase could not be found in the catalog." },
	{ "Errors_6000.90", "The game you requested is not installed.  Please re-install and try again." },
	{ "Errors_6001.11", "This email address has already been used on a Social Club account. Please try a different email address. If you are the owner of this email address and have forgotten your password, you can <a>request to reset your password</a>." },
		{ "Errors_6001.198", "This email has already been verified, use the \"Check Verification\" button to proceed" },
	{ "Errors_6001.27", "This nickname has already been used on a Social Club account. Please try a different Nickname." },
	{ "Errors_6001.86", "You are already a member of this crew." },
	{ "Errors_6002.45", "We could not send you a password reset confirmation email at this time due to a Rockstar Game Services error. Please try again later." },
	{ "Errors_6003", "Error deserializing the data due to a Rockstar Game Services error.  Please try again later." },
	{ "Errors_6003.66", "The Store is currently unable to complete your order.  Please try again later." },
	{ "Errors_7000", "The Store is currently unavailable.  Please try again later." },
	{ "Errors_7000.66", "The Store is currently unable to complete your order.  Please try again later." },
	{ "Errors_7000.71", "The Steam store is currently unavailable.  Please try again later.  If the issue persists, please contact <a>Steam Support</a>." },
	{ "Errors_7000.90", "The Store is currently unable to install your product. Please try again later." },
	{ "Errors_7001", "An activation service error occurred. Please try again later. If the error persists, please visit our <a>Service Status</a> page." },
	{ "Errors_7001.70", "Unable to use the voucher. Please try again later." },
	{ "Errors_7002", "Game launch error. Please try again later." },
	{ "Errors_7002.110", "The request has timed out whilst attempting to determine title. Please try again later." },
	{ "Errors_7002.49", "Unable to locate Steam account name for account linking. Please try again later." },
	{ "Errors_8000", "Too many requests are being made from your IP address. Wait a few minutes and try again." },
	{ "Errors_9000.79", "Unable to send message because this user is on your block list." },
	{ "Errors_9000.92", "Unable to send message because you have been blocked by this player." },
	{ "Errors_AccountExists", "Account already exists with the given Email or Nickname." },
	{ "Errors_ActivationLegalCheck", "Checkbox must be completed to continue" },
	{ "Errors_AnErrorOccurred", "An error occurred" },
	{ "Errors_AuthAttempts", "Please complete the captcha." },
	{ "Errors_AuthTokenInvalid", "We could not create a sign in token. Please try again later. If the error persists, please visit the <a>Rockstar Support website</a>" },
	{ "Errors_Cancel", "Cancel" },
	{ "Errors_CaptchaErrorExpired", "CAPTCHA challenge has expired. Please try again." },
	{ "Errors_CaptchaErrorInvalid", "Missing or Invalid CAPTCHA. Please ensure you have installed the latest updates and try again. If the issue persists, visit the <a>Rockstar Games Support</a> website for help." },
	{ "Errors_CaptchaErrorUnknown", "There was an unexpected problem verifying the CAPTCHA challenge. If the issue persists, visit the <a>Rockstar Games Support</a> website for help." },
	{ "Errors_CaptchaOffline", "There was a error contacting the CAPTCHA service. Please <retry-link>retry</retry-link>." },
	{ "Errors_Close", "Close" },
	{ "Errors_Code", "Code" },
	{ "Errors_ConProblem", "There may be a connection problem with your network." },
	{ "Errors_ConfirmButtonText", "Confirm" },
	{ "Errors_ConfirmMatch", "Confirmation does not match password." },
	{ "Errors_ConnectLost", "Connection Lost" },
	{ "Errors_ConnectionUpdate", "Connection Update" },
	{ "Errors_CrewGeneralServiceError", "An error has occurred, please check your internet connection, and try again." },
	{ "Errors_CrewNoMembersSuffix", "currently has no members." },
	{ "Errors_DisconnectRefresh", "You have been disconnected from the Social Club. The UI will refresh to reflect this." },
	{ "Errors_DuplicateSignedOut", "You have been logged out because your account ({nickname}) has logged in elsewhere." },
	{ "Errors_EmailDoesNotMatch", "Confirmation does not match email." },
	{ "Errors_EmailExists", "Email already in use." },
	{ "Errors_EmailNotFound", "Email address not found." },
	{ "Errors_EnterActivation", "Please enter Rockstar Activation Code." },
	{ "Errors_EnterNick", "Please enter a Nickname." },
	{ "Errors_EnterPassword", "Please enter your password." },
	{ "Errors_EnterRedemption", "Please enter Rockstar Activation Code." },
	{ "Errors_Entitlement_i-1", "An activation service error occurred. Please try again later. If the error persists, please visit our <a>Service Status</a> page." },
	{ "Errors_Entitlement_i38", "Rockstar Activation Code already in use." },
	{ "Errors_Entitlement_i39", "Rockstar Activation Code is not valid." },
	{ "Errors_Entitlement_i40", "Error contacting redemption server. Please check your connection or try again later." },
	{ "Errors_Entitlement_i46", "Activation authentication failure, please try restarting the game." },
	{ "Errors_Entitlement_i47", "Sorry, that code requires another product to be installed first such as the main game." },
	{ "Errors_Entitlement_i48", "The code entered cannot be redeemed from your current location. Select Rockstar codes are only valid in specific countries. See <a>Rockstar Support</a> for details" },
	{ "Errors_EntryDOB", "Please enter date of birth." },
	{ "Errors_EntryEmail", "Please enter your email address." },
	{ "Errors_EntryPassword", "Please enter your password." },
	{ "Errors_EpicAlreadyLinked", "This Epic Games account is already linked to a different Social Club account.  Please log in with that Social Club account instead." },
	{ "Errors_Error", "Error" },
	{ "Errors_ErrorActivate", "Error trying to activate." },
	{ "Errors_ErrorHasOccurred", "Sorry, an error has occurred." },
	{ "Errors_ErrorPassword", "Error updating password." },
	{ "Errors_ErrorSupport", "Please try again later. If the error persists, please visit the <as>Rockstar Support website</as> and stay tuned to <ss>Service Status Updates</ss>." },
	{ "Errors_ErrorUpdate", "Error updating profile: Password invalid or incorrect." },
	{ "Errors_FeatureDisabled", "Feature Temporarily Disabled" },
	{ "Errors_FeatureDisabledDesc", "Sorry, this feature is not currently supported. Please check back again later." },
	{ "Errors_GenericError1", "We're sorry. Based on the information you have submitted to us, you are not eligible to register for the Social Club. Please see our <ap>Privacy Policy</ap>. If you feel that this is an error, you can contact <as>Rockstar Games Support</as>." },
	{ "Errors_GenericFriendActionError", "Sorry, the request failed, please try again later." },
	{ "Errors_GenericServerError", "An unknown Rockstar Game Services error occurred. Please try again later." },
	{ "Errors_IncorrectPassword", "Incorrect password, please retry." },
	{ "Errors_InternetAccess", "Please ensure you have internet access and try again." },
	{ "Errors_InvalidCreateAccountError", "There was a problem when trying to create your account." },
		{ "Errors_InvalidPassPattern", "Alphanumeric or these characters only \"{ chars }\"" },
	{ "Errors_InvalidPassword", "You entered an invalid password.  Please remove any special characters and try again." },
	{ "Errors_InvalidPasswordNew", "Password must contain {min}-{max} characters with at least one number, one uppercase character and one lowercase character. Please amend your password and try again." },
	{ "Errors_InvalidZip", "Invalid Zip Code" },
	{ "Errors_Loading", "Loading*" },
	{ "Errors_Maintenance", "Scheduled Maintenance" },
	{ "Errors_MaxNoCrewsExceeded", "You have exceeded the maximum number of Crews." },
	{ "Errors_MessageMissing", "Message is required." },
	{ "Errors_MfaCodeInvalid", "Invalid Verification Code, please try again." },
	{ "Errors_MfaCodeMissing", "Please enter your Verification Code." },
	{ "Errors_MfaResetError", "Sorry, we are unable to handle your request at this time. Please try again later." },
	{ "Errors_NetworkDetected", "Network connection detected" },
	{ "Errors_NickChar", "Nickname must be between 6 and 16 characters." },
	{ "Errors_NickExists", "Nickname already in use." },
	{ "Errors_NickInvalid", "Invalid characters in Nickname." },
	{ "Errors_NicknameMissing", "Nickname is required." },
	{ "Errors_NoActiveCrew", "You currently have no active Crew set." },
	{ "Errors_NoCon", "No Connection" },
	{ "Errors_NoData", "No Data" },
	{ "Errors_NoInternet", "The game failed to connect to the Internet.  Online features and DLC may not be available.  Please try the following:{linebreak}{linebreak}Open a web browser to verify that you have an active Internet connection.<br>\r\nIf you have separate modem and router boxes, bypass your router and connect instead to the modem (the other box) directly using a wired Ethernet cable to test if your router is the problem.<br>\r\nIf you have a combination modem/router in one unit, try putting it in Bridge Mode." },
	{ "Errors_NoMatchCrewMembers", "No matching Crew members found." },
	{ "Errors_NoMatchSCMembers", "No matching Social Club members found." },
	{ "Errors_NoMatches", "No matches found. Please try again using another search term." },
	{ "Errors_NoStatsExist", "No players stats exist yet." },
	{ "Errors_NotAccess", "We're sorry, data is not accessible" },
	{ "Errors_NotFound", "Username not found or password is invalid." },
	{ "Errors_NotFoundEmail", "Email not found or password is invalid." },
	{ "Errors_OfflineBut", "You are offline but your online connection has become available again. Would you like to go back online?" },
	{ "Errors_OfflineSigninError", "Error: The username or password may be wrong or the account may not exist on this machine. Offline play is only available for accounts that have previously signed in on this machine (with \"Remember me\" ticked) while connected to the Internet and while Social Club Services are available." },
	{ "Errors_OfflineSigninErrorNoProfiles", "Error: We were unable to fallback to offline sign in because you have not previously signed in on this machine. Offline play is only available for accounts that have previously signed in on this machine (with \"Remember me\" ticked) while connected to the Internet and while Social Club Services are available." },
	{ "Errors_OnlineDisabled", "Sorry, Social Club is currently experiencing technical difficulties and online services have been temporarily disabled." },
	{ "Errors_PasswordCount", "Invalid password length. Password must contain {min}-{max} characters with at least one number, one uppercase character and one lowercase character. Please amend your password and try again." },
	{ "Errors_PasswordSame", "New password must be different from your current password." },
	{ "Errors_PasswordUpdate", "Your current password is not strong enough. Please enter a new password." },
	{ "Errors_PrivacySettingFailure", "Failed to update privacy setting." },
	{ "Errors_ProductUrlNotFound", "Error retrieving product url." },
	{ "Errors_ProfileNotFound", "Selected Profile not found." },
	{ "Errors_RL_SC_FRIENDS_ERR_ALREADY_BLOCKED", "Unable to block this player because they are already on your block list." },
	{ "Errors_RL_SC_FRIENDS_ERR_ALREADY_FRIENDS", "Unable to perform this action because you are already friends." },
	{ "Errors_RL_SC_FRIENDS_ERR_AUTHENTICATION_FAILED", "Sorry, an error occurred during authentication, please try again later." },
	{ "Errors_RL_SC_FRIENDS_ERR_BLOCKER_FRIEND_LIMIT_REACHED", "Unable to perform this action because your block list is full." },
	{ "Errors_RL_SC_FRIENDS_ERR_BLOCK_DOES_NOT_EXIST", "Unable to unblock player because they are not currently on your block list." },
	{ "Errors_RL_SC_FRIENDS_ERR_FRIEND_DOES_NOT_EXIST", "Unable to perform this action because you are not currently friends with this player." },
	{ "Errors_RL_SC_FRIENDS_ERR_FRIEND_INVITE_BLOCKED", "Unable to perform this action because you have been blocked by this player." },
	{ "Errors_RL_SC_FRIENDS_ERR_FRIEND_INVITE_DOES_NOT_EXIST", "Unable to perform this action because the friend invite could not be found." },
	{ "Errors_RL_SC_FRIENDS_ERR_FRIEND_INVITE_EXISTS", "Unable to perform this action because a friend request already exists between you and this player." },
	{ "Errors_RL_SC_FRIENDS_ERR_INVALID_INVITEE_ID", "Unable to perform this action because the requested player account could not be found." },
	{ "Errors_RL_SC_FRIENDS_ERR_INVITEE_FRIEND_LIMIT_REACHED", "Sorry, you have reached the maximum number of friends permitted." },
	{ "Errors_RL_SC_FRIENDS_ERR_INVITER_FRIEND_LIMIT_REACHED", "Unable to accept invite because the inviter has exceeded the maximum number of friends permitted." },
	{ "Errors_RL_SC_FRIENDS_ERR_INVITE_DOES_NOT_EXIST", "Friend invite does not exist; it may have been cancelled by the inviter." },
	{ "Errors_RL_SC_FRIENDS_ERR_PENDING_SENT_LIMIT_REACHED", "Unable to perform this action because you have exceeded the maximum number of pending friend invites permitted." },
	{ "Errors_RecaptchaResponsePlaceholder", "Type the text" },
	{ "Errors_RecaptchaTerms", "Privacy & Terms" },
	{ "Errors_ReportError", "An error occurred during report submission." },
	{ "Errors_Retry", "Retry" },
	{ "Errors_RockstarAlreadyLinked", "This Social Club account is already linked to a different Steam account. Please log out of Steam and log in on the Steam account linked to this Social Club account." },
	{ "Errors_SC_Down", "Social Club Services are currently experiencing technical difficulties.{linebreak}{linebreak}No problems were detected with your Internet connection" },
	{ "Errors_SearchMin3Chars", "Search must contain a minimum of 3 characters" },
	{ "Errors_SelectAvatar", "Please select an Avatar." },
	{ "Errors_ServerError", "Server error" },
	{ "Errors_SettingsCountryLoadFailed", "ERROR: Failed to load country list. Please try again later." },
	{ "Errors_SignInFailure", "Sign in failure" },
	{ "Errors_SignInPasswordCount", "Password must contain {min}-{max} characters." },
	{ "Errors_SignUpCountryLoadFailed", "ERROR: Failed to load country list. Unable to create a new Social Club account at this time. Please try again later." },
	{ "Errors_SlowServiceMessage", "Sorry, this is taking longer than expected." },
	{ "Errors_SorryTry", "We apologize for this problem, please try again later." },
	{ "Errors_SteamAlreadyLinked", "This Steam account is already linked to a different Social Club account.  Please log in with that Social Club account instead." },
	{ "Errors_TermsofService", "Terms of Service" },
	{ "Errors_TooManyLoginAttempts", "Your account has been locked due to repeated failed sign in attempts." },
	{ "Errors_UnableConnect", "Unable to connect to the network" },
	{ "Errors_UnknownCreateAccountError", "Unknown error creating this account." },
	{ "Errors_UnknownError", "Unknown Error" },
	{ "Errors_UserBanned", "This account has been restricted due to violating the Rockstar Games [Terms of Service]." },
	{ "Errors_ValidDOB", "Please enter valid date of birth." },
	{ "Errors_ValidEmail", "Enter a valid email address." },
	{ "Errors_reqest_CheckPassword", "Check password" },
	{ "Errors_request_AccountSearch", "Account search" },
	{ "Errors_request_BindSteamAccount", "Bind Steam Account" },
	{ "Errors_request_CrewMembers", "Crew members" },
	{ "Errors_request_DeleteMessage", "Delete message" },
	{ "Errors_request_EmailAvailable", "Email availability check" },
	{ "Errors_request_GetAvatarXml", "Get avatar XML" },
	{ "Errors_request_GetAvatars", "Get avatars" },
	{ "Errors_request_GetCommunityStats", "Community Stats" },
	{ "Errors_request_GetCountries", "Get countries" },
	{ "Errors_request_GetCrewInvites", "Get Crew invites" },
	{ "Errors_request_GetCustomAvatars", "Get custom avatars" },
	{ "Errors_request_GetEulaOffline", "Get EULA offline" },
	{ "Errors_request_GetFriendAchievements", "Get friend achievements" },
	{ "Errors_request_GetFriendInvites", "Get friend invites" },
	{ "Errors_request_GetFriendProfile", "Get friend profile" },
	{ "Errors_request_GetFriendProfileCrews", "Get Crews for friend profile" },
	{ "Errors_request_GetFriends", "Get friends" },
	{ "Errors_request_GetMessageSenderList", "Get message sender list" },
	{ "Errors_request_GetMessages", "Get messages" },
	{ "Errors_request_GetPlayerStats", "Get player stats" },
	{ "Errors_request_GetPrivacyPolicy", "Get privacy policy" },
	{ "Errors_request_GetTos", "Get terms of service" },
	{ "Errors_request_GetUserAccountInfo", "Get user account info" },
	{ "Errors_request_MyCrews", "Get my Crews" },
	{ "Errors_request_NicknameAvailable", "Nickname availability check" },
	{ "Errors_request_ResetPassword", "Reset password request" },
	{ "Errors_request_SearchCrewMembers", "Search Crew members" },
	{ "Errors_request_SearchCrews", "Search Crews" },
	{ "Errors_request_SendMessage", "Send message" },
	{ "Errors_request_SubmitProfileReport", "Submit Profile Report" },
	{ "Errors_request_UpdateAvatar", "Update avatar" },
	{ "Errors_request_UpdateCountry", "Update country" },
	{ "Errors_request_UpdateDob", "Update DOB" },
	{ "Errors_request_UpdateDobCountry", "Update DOB and country" },
	{ "Errors_request_UpdateEmail", "Update email" },
	{ "Errors_request_UpdateNickname", "Update nickname" },
	{ "Errors_request_UpdatePassword", "Update password" },
	{ "Errors_request_UpdatePrivacySettings", "Update privacy settings" },
	{ "Errors_request_UpdateProfile", "Update profile" },
	{ "Errors_request_UserNetworks", "Get user networks" },
	{ "Errors_request_ValidateAccountDetails", "Validate Account Details" },
	{ "Errors_timeout", "The request has timed out." }
};
